services:
  app:
    platform: linux/amd64
    build:
      context: ../../
      dockerfile: config/docker/Dockerfile
    container_name: capstone-container
    command: sleep infinity
    ports:
      - "8000:8000"
    volumes:
      - ../../:/app
    environment:
      - PYTHONPATH=/app
